name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ethereum:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd evm && bash ../scripts/install_foundry.sh
      - run: cd evm && PATH=$PATH:$HOME/.foundry/bin/ make dependencies
      - run: cd evm && PATH=$PATH:$HOME/.foundry/bin/ && source env/testing.env && ETH_FORK_RPC=${{ secrets.ETH_RPC }} forge test --fork-url ${{ secrets.ETH_RPC }}
